version: '3.7'
services:
  db:
    image: mysql:8
    container_name: swift_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: swift_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
     - ./initdb:/docker-entrypoint-initdb.d
  app:
    build: .
    container_name: go-server
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: swift_db
    ports:
      - "8080:8080"
    depends_on:
      - db
